CREATE TABLE Phrase(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 WHO VARCHAR(3000),
 TIME_WHEN VARCHAR(3000), 
 DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 
 CREATE TABLE JOKE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 
  CREATE TABLE WORD(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
WORD_ITSELF VARCHAR(3000),
 DEFINITION_DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 
 CREATE TABLE RECIPE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
CREATOR_TRAINER VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
DEFINITION_DETAILS2 TEXT, 
DEFINITION_DETAILS3 TEXT, 
IMAGE_ID VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
CREATE TABLE VIDEOTUBE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
SOURCE_URL VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
 CREATE TABLE PHOTOSTAND(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
SOURCE_URL VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
CREATE TABLE IINTELNEWS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
HEADING VARCHAR(3000),
DEFINITION_DETAILS TEXT, 
SOURCE_URL VARCHAR(3000),
SOURCE VARCHAR(3000));
 

CREATE TABLE IINTEL_RECORDS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
PHRASE_ID INT NOT NULL,
JOKE_ID INT NOT NULL,
WORD_ID INT NOT NULL,
RECIPE_ID INT NOT NULL,
VIDEOTUBE_ID INT NOT NULL,
PHOTOSTAND_ID INT NOT NULL,
IINTELNEWS_ID INT NOT NULL);

drop table IINTEL_RECORD_ITEM
CREATE TABLE IINTEL_RECORD_ITEM(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
IINTEL_RECORDS_ID INT NOT NULL, 
PHRASE_ID INT NOT NULL,
JOKE_ID INT NOT NULL,
WORD_ID INT NOT NULL,
RECIPE_ID INT NOT NULL,
VIDEOTUBE_ID INT NOT NULL,
PHOTOSTAND_ID INT NOT NULL,
IINTELNEWS_ID INT NOT NULL);